{% set name = "tensorflow-text" %}
{% set version = "2.19.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name.split('-')[0] }}/{{ name.split('-')[1] }}/archive/v{{ version }}.tar.gz
  sha256: c06c97ebe5b15250a12bddbab094b13f048a20ff0b8a4967bb03c5f4d57fe3f8
  patches:
    - patches/0001-Bazel-parallel-build-removed-added-server-cleanup-af.patch
    - patches/0002-Remove-setuptools-hard-pin.patch
    - patches/0003-Unvendor-tensorflow.patch
    - patches/0004-Help-bazel-find-correct-SDKROOT-before-run-command.patch
    # https://github.com/AnacondaRecipes/tensorflow-feedstock/blob/647150fb3ff128a8b7d4a15ce345c1f65b919948/recipe/patches/0020-is_signed-cannot-be-specialized.patch
    # Attribute is_signed removed from the tensorflow version 2.20, but not in the 2.19, all we can do it is just use -Wno-invalid-specialization
    - patches/0005-add-std-is_signed-compatibility-with-new-libc.patch
    # BUILD.bazel:51:11: Compiling src/bpe_model.cc failed: undeclared inclusion(s) in rule '@com_google_sentencepiece//:sentencepiece_processor'
    # this rule is missing dependency declarations for the following files included by 'src/bpe_model.cc'
    - patches/0006-fix-cppmap-errors-with-newer-clang.patch
    #import tensorflow_text
    #File "lib/python3.10/site-packages/tensorflow_text/__init__.py", line 20, in <module>
    #  from tensorflow_text.core.pybinds import tflite_registrar
    #ImportError: lib/python3.10/site-packages/tensorflow_text/core/pybinds/tflite_registrar.so: undefined symbol: _ZN4absl12lts_2023080216raw_log_internal21internal_log_functionB5cxx11E
    #- patches/0007-Override-abseil-cpp-to-use-version-20250127-instead-.patch
    - patches/0007-unvendor-only-abseil.patch
    # error: 'StrCat' is not a member of 'absl'
    #- patches/0008-Add-str_cat-missing-includes.patch
    - patches/0008-Added-missing-include-and-dependency-for-absl-strcat.patch
    #- patches/0009-link-tesorflow-from-run_build.patch
    - patches/0010-Add-configuration-to-use-conda-bazel-toolchain.patch

build:
  number: 0
  missing_dso_whitelist:
    # Linux
    - $RPATH/libtensorflow_framework.so.2  # [linux]
    - '*/libdl.so.*'                       # [linux]
    - '*/libpthread.so.*'                  # [linux]
    - '*/libm.so.*'                        # [linux]
    - '*/libstdc++.so.*'                   # [linux]
    - '*/libgcc_s.so.*'                    # [linux]
    - '*/libc.so.*'                        # [linux]
    - '*/ld-linux-aarch64.so.*'            # [linux]
    # macOS
    - $RPATH/libtensorflow_framework.2.dylib  # [osx]
  ignore_run_exports:
    - libabseil                            # [osx]
    - libcxx                               # [osx]
    - zlib                                 # [osx]
  # Latest version of supported python 3.12, look requirements_lock files
  skip: true  # [py>312]
  # TODO: add support for windows
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel <7
    - bazel-toolchain >=0.4.1  # [not win]
    - git
  host:
    - pip
    - python
    - setuptools >=70.0.0,<76
    - wheel
    # The version of tensorflow has to match the version of tensorflow-text
    - tensorflow ==2.19.1
    - _tflow_select 2.3.0 {{ tensorflow_flavor }}
    - libabseil 20250127.*
  run:
    - python
    - tensorflow >=2.19.0,<2.20    
    - _tflow_select * {{ tensorflow_flavor }}
    - libabseil 20250127.*
  run_constrained:
    - tensorflow-datasets >=3.2.0
    - tensorflow-cpu >=2.19.0, <2.20
    - tensorflow-hub >=0.16.1

test:
  imports:
    - tensorflow_text
  requires:
    - pip
  commands:
    - pip check
    - conda inspect linkages -p $PREFIX tensorflow-text

about:
  home: https://github.com/tensorflow/text
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - tensorflow_text/core/kernels/LICENSE
    - oss_scripts/pip_package/LICENSE
  summary: TensorFlow is a machine learning library, base package contains only tensorflow.
  description: |
    TensorFlow Text provides a collection of text related classes and ops ready to use with TensorFlow 2.0. The library
    can perform the preprocessing regularly required by text-based models, and includes other features useful for
    sequence modeling not provided by core TensorFlow.
  dev_url: https://github.com/tensorflow/text
  doc_url: https://github.com/tensorflow/text/blob/master/README.md